### PR TITLE
Fix comment in ``OddOneOut`` task

### PR DESCRIPTION
**Pull request by linus-md**

### CODE REVIEW

**Comment by samwinebrake** [comment]
disable result caching in om

**Comment by linus-md** [comment]
What is the problem here @samwinebrake?  :sweat_smile:

**Comment by samwinebrake** [comment]
> What is the problem here @samwinebrake? 😅

@linus-md Hahaha since this typo fix is within a model_helpers file, it triggers all of our unit testing suite. I've been using it as a trigger to retest different changes I've been making to fix these tests! Apologies for all of the notifications, we're very close to having everything pass!

**Comment by samwinebrake** [comment]
testing log changes

**Comment by samwinebrake** [comment]
testing jenkins restart

**Comment by samwinebrake** [comment]
removing tf tests for now

**Comment by linus-md** [comment]
@deirdre-k the typo still persist if I am not mistaken

**Comment by deirdre-k** [comment]
Apologies, I read the git conflict wrong. Reopening now!

**Pull request merged**
