### PR TITLE
unify @ynshah3's cornet submissions into one plugin

### PR DESCRIPTION
**Pull request by mschrimpf**
@ynshah3 please see if this makes sense to you (cleaning up the directory namespace)

### CODE REVIEW

**Review by mike-ferguson — APPROVED** [review]
looks good, pending @ynshah3's approval and tests passing.

**Review by ynshah3 — APPROVED** [review]
LGTM!! Whoa that are a lot of files - sorry for not taking the initiative myself, and thank you @mschrimpf!

**Comment by mschrimpf** [comment]
all good, this is on our submission system for not being able to handle that many files at once

**Comment by mschrimpf** [comment]
hi @ynshah3, the tests are running into 
```
urllib.error.HTTPError: HTTP Error 404: Not Found
```
I can reproduce this locally. As far as I can tell, this is not an issue with the code change because the previous code also does not work, e.g.
```
    url = f'https://storage.googleapis.com/neurodp/0_0_0_ckpt.pt'
    ckpt_data = torch.hub.load_state_dict_from_url(url)
```
Did the files get moved?

**Comment by mschrimpf** [comment]
@ynshah3 pinging this again

**Pull request merged**
