### PR TITLE
Add sparse objects benchmark

### PR DESCRIPTION
**Pull request by benlonnqvist**
This PR adds the sparse objects benchmark (yet unpublished) by Elsa Scialom and Ben Lonnqvist.

Todo list:
- [x] Add AccuracyDistance benchmarks
- [x] Add ErrorConsistency composite benchmark
- [x] Add Engineering benchmark
- [x] Add benchmark tests
- [x] Prepare experimental data assembly packaging
- [x] Prepare stimulus packaging
- [x] Add stimulus and assembly tests
- [x] Add AccuracyDistance metric
- [x] Add metric tests
- [x] Add AccuracyDistance human ceilings
- [x] Add ErrorConsistency composite human ceiling
- [x] Upload pre-computed .nc files to S3
- [x] Retrieve stimulus_set and assembly hashes and version_ids
- [x] Upload assembly and stimulus packaging to S3

### CODE REVIEW

**Comment by benlonnqvist** [comment]
It seems that Jenkins, and Jenkins plugin tests are being skipped for some reason (#668).

**Comment by samwinebrake** [comment]
Added permissions to access benchmarks within aws brainscore-vision bucket

**Comment by mschrimpf** [comment]
The private Travis run fails because forks do not have access to repository secrets

**Comment by mschrimpf** [comment]
For the public Travis run: are the tests using files with private access? If yes, you need to mark them as `@pytest.mark.private_access` so that they are not run with the public settings

**Comment by benlonnqvist** [comment]
@mschrimpf I don't think anything should be using files with private access (at least, I have nowhere intentionally specified any of the files to be private).

**Comment by mschrimpf** [comment]
private tests on travis are failing as expected because fork PRs do not have access to secrets. They all pass on Jenkins though

**Review by mschrimpf — APPROVED** [review]

**Pull request merged**
