### PR TITLE
Github Actions Workflow to keep develop synchronized with changes from master

### PR DESCRIPTION
**Pull request by KartikP**
Trigger conditions is when any PR targeting `master` is closed. Additional trigger to determine if web submission PR (for `auto_sync...`) or not a web submission PR (for `create_pr...`). 

`create_pr_for_nonplugin` will create a PR to synchronize master to develop.
`auto_sync_for_plugin` will attempt to automatically merge the `develop` branch onto `master` branch and then pushes changes to `develop`. If unsuccessful, a PR will be created to address the merge conflict.

This workflow does not contain steps that push or merge changes back onto the `master` branch and all actions are performed on `develop` so there should be no unintended changes to `master`

### CODE REVIEW

**Comment by KartikP** [comment]
Promise this is my last trigger.

**Comment by KartikP** [comment]
If I swap rebase with merge. I get the following issue:
`  
Configured git committer as 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
Configured git author as 'KartikP <2040394+KartikP@users.noreply.github.com>'
Create or update the pull request branch
 /usr/bin/git symbolic-ref HEAD --short
 fatal: ref HEAD is not a symbolic ref
 /usr/bin/git rev-parse HEAD
394f6cea9ca4e4cc1a0f3a91a992bfd51bfa1762
Working base is commit '394f6cea9ca4e4cc1a0f3a91a992bfd51bfa1762'
/usr/bin/git checkout --progress -B 10392f9f-b6ef-4f64-b581-da47a89de0b4 HEAD --
error: you need to resolve your current index first
README.md: needs merge
Error: The process '/usr/bin/git' failed with exit code 1
`

**Comment by KartikP** [comment]
Swapped out rebase with merge.

**Review by samwinebrake — APPROVED** [review]
LGTM as long as tested locally :)

**Pull request merged**
