### PR TITLE
Tweak odd-one-out task

### PR DESCRIPTION
**Pull request by linus-md**
Use ReLU'ed model activations

### CODE REVIEW

**Review by mschrimpf — COMMENTED** [review]
@linus-md sorry for missing this PR. We have already run several models without ReLU'ing activations -- should we still merge this and re-run?

**Comment by linus-md** [comment]
I would say this is somewhat up for debate. Martin H. suggested this in the spirit that negative activations are noise. As far as I know most models use relu natively in the penultimate layer so it should not make a difference in most cases. Also if a researcher chooses not to use relu this should maybe be respected. What do you say?

**Comment by mschrimpf** [comment]
> if a researcher chooses not to use relu this should maybe be respected. 

that's exactly how I was thinking about it too. Your original implementation is more flexible and leaves the choice to the modeler.

**Comment by linus-md** [comment]
Ok good I'll close this then.

**Pull request closed without merging**
